# Generated by Django 2.2.11 on 2022-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrdata',
            fields=[
                ('employee_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=50)),
                ('department_id', models.CharField(max_length=10)),
                ('supervisor_id', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
